export const FETCH_CLIENTS = 'FETCH_CLIENTS';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const ADD_CLIENTS = 'ADD_CLIENTS';
export const ADD_CLIENTS_SUCCESS = 'ADD_CLIENTS_SUCCESS';
export const CLEAR_DB = 'CLEAR_DB';
export const CLEAR_DB_SUCCESS = 'CLEAR_DB_SUCCESS';
